 
splash.lss

Type: <ENTER> to start the installation.

---------------------------------------------------------
WARNING: All data will be erased and the disks formatted.
         To perform a manual format of hard disk(s),
         Type: manual-format <ENTER>
---------------------------------------------------------

Root password is "setup".

02[F1-Main] [F2-Options] [F3-General] [F4-Kernel]07
